apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: redis-cluster-system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      serviceAccountName: controller-manager
      containers:
      - name: manager
        image: controller:latest
        imagePullPolicy: IfNotPresent
        args:
        - --leader-elect
        ports:
        - name: metrics
          containerPort: 8080
        - name: health
          containerPort: 8081
        livenessProbe:
          httpGet:
            path: /healthz
            port: health
        readinessProbe:
          httpGet:
            path: /readyz
            port: health
